### ISSUE TITLE
Previsualización al enviar el enlace

### ISSUE THREAD

**Issue by elenafernandezweb** [inittab/onetimepaste#4]
Hola, buenos días.
Estamos probando esta aplicación, y vemos que al enviar el enlace por email o por whatsapp, cuando abrimos el enlace después de enviarlo, la aplicación indica que el mensaje ya ha sido leído.
Según pruebas realizadas, creemos que es por la previsualización que realizan las aplicaciones por las que enviamos el enlace.
Por favor, ¿podrías indicarnos cómo ampliar la visualización del mensaje a 2 veces, en lugar de a una vez? Así nos saltaríamos el problema que hay con la previsualización.

**Comment by inittab** [comment]
Buenos días,
El objetivo de que sólo se pueda ver es ser consciente de que alguien (o algo) ha visto la información, que se supone confidencial. Cuando el proveedor de correo, o whatsapp, ven el enlace, estos pasan a tener esa información que esperabas quedase privada. Mi recomendación es que añadas un texto fácilmente reconocible por un humano y que indique que debe ser quitado del enlace para abrir. Por ejemplo, si tienes este enlace:
https://onetimepaste.midominio.com/index.php?id=87hkhdiq3hdnaskd8qd3qwe
Puedes enviar este otro enlace:

https://onetimepaste.midominio.com/index.php?id=87hkhdiq3hdnaskd8qd3qwe__QUITA_ESTO__
E indicar en tu correo que deben quitar "__QUITA_ESTO__" para abrir el enlace. De esa forma los servicios que lo abren automáticamente no lo harán con el código correcto.

**Comment by elenafernandezweb** [comment]
Mira tú, qué solución tan práctica y sin tocar código.
Millones de gracias, acabamos de hacer la prueba y funciona correctamente.
Un saludo, y gracias de nuevo!!
